install: true
addons:
  sonarcloud:
    organization: "projectbarbel" 
    token:
      secure: H5ukGRvpbikcOGTXw+Ynn/+jeRMdluy/YfVnaMuiBHtHv2bAmrL7XhxdK/F1E5WtGWbI62Ab6zBUW3VA1CddFVZZgziORPbIHwXI2H5WtgjUxSDzFuTmnoALpDSQB6GhKrd7oD8igVyX4nwamk44bbJHW+ac6uZq84z4OMCfsHP85pQ1tDGteeMZwHaR6oR8vsBjbwaUjHyUEtHsE/0hLqrxwMC6F15wdyAkGdwRecFirHYWpHyLVCUZBXA5Q6rExN0VtvtKqR0QDL8HtO9YnhkZVD2l7MyzbEOxmuRQfydH3C317wguc5+laZDOwiZ22sfU5l2/2qS4V29I+b44POJjfAlLVSHzH1sFs03h/lDezO6CHQu4sIVanlh4LFfEADhubCBtLDQOmxG1ihPS7SkFHrOuEsolnx+qHU8sJn/kV2H6Ee3X6eUtD16zEFliZPQ9EiTaaPi/EciiODip8bTSEzIUq2swLI0c58HoanjfrauGwWDK9VuppfvaxgclrKd4O/tdsUMIPdGlJ0dbPfipL3JZMR5jGeKHjaUgulW4esLh6hDORT3tiXsV+CZinzsqzrzbj1PbgpIgZdN5FaRhya6aErkjBFlGbD7Inx5GFsFXkZ+SiD1BeWKFi1RCXLA+kNcafhLMdOZeX2qz1Gh+dDvQCYJ3RZkKGwnc8Pc=
before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
- echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install: mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -P release
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
deploy:
  overwrite: true
  provider: releases
  api_key:
    secure: T/KE9zhQwZyQze8EjOepNHAoagnBB57yLM+l35iRX6y/eZMIXBfuPBKRM3NIUk7YfTzYbFG4SdaGz4n7WwItqrCgjF7jglnXKy/aSm3PNZKf/wnNRQAQiHJmpkugeaC0EMS3ckKpfhEMhYxQRhcu0ih2h9PKzHtSbHJSS1bf/kb2Qdln8UG3dDBlOfmHR4IbNboo2eXUZUtVQObU1gLikPVYs6nEBZnmp/RNXhEFe4Fivm7tiF6I2qq56fasauyjyq2vAFqnfg0E1hAVzdF70PDBvJrWNjyqhSes2CAw/QnhxQ52wNYKfecfVTebbGIynnGIY8/xmPqRXMzw6ffW/NydpJeF4nUqmqEiYf5a7YrhFd9HPnZrYAgezlH2VO7iimccNaqWr/SUeBQPhCyUd+aovPlq/IVlv9ynlWZ/Ay6dzQFD6Wl2WYDecQXherHXiz045pGsB+NOFYjuWqsf40vYKTbfoQkxOKN1LSLoGotfpzblL60TESpYloiy+pJX9rRJ8d0o6oH6lXoqiVPUJK18WdkNkmLfOGAOXa2W6TzoOpaRDdE7XoXa2eoIVC8b95h8EUgNAfYZNs+ipDpNfeDvWrhM5QzF2VroOoamWFbdtWMxDY1w1BAviLjhk3JMe0rMxm2x3IFEZkbzlTnBWs4nq79MCOk5reJh5LsqU4s=
  file: 
      - target/barbelhisto-persistence-mongo-$project_version.jar
      - target/barbelhisto-persistence-mongo-$project_version-sources.jar
      - target/barbelhisto-persistence-mongo-$project_version-javadoc.jar
  on:
    repo: projectbarbel/barbelhisto-core
    tags: true
  name: $project_version
